"""Initial Tables

Revision ID: 4447a557dae4
Revises: 
Create Date: 2021-05-25 20:54:45.256019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4447a557dae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_slug'), 'country', ['slug'], unique=False)
    op.create_table('live_stock_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('turnover', sa.Float(precision=2), nullable=True),
    sa.Column('volume', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_exchange_name'), 'securities_exchange', ['name'], unique=False)
    op.create_index(op.f('ix_securities_exchange_slug'), 'securities_exchange', ['slug'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('securities_exchange_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['securities_exchange_id'], ['securities_exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_ticker_symbol'), 'company', ['ticker_symbol'], unique=False)
    op.create_table('historical_stock_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('high_price', sa.Float(precision=2), nullable=True),
    sa.Column('low_price', sa.Float(precision=2), nullable=True),
    sa.Column('closing_price', sa.Float(precision=2), nullable=False),
    sa.Column('turnover', sa.Float(precision=2), nullable=True),
    sa.Column('volume', sa.Float(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_stock_data_company_id'), 'historical_stock_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_historical_stock_data_date'), 'historical_stock_data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_stock_data_date'), table_name='historical_stock_data')
    op.drop_index(op.f('ix_historical_stock_data_company_id'), table_name='historical_stock_data')
    op.drop_table('historical_stock_data')
    op.drop_index(op.f('ix_company_ticker_symbol'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_securities_exchange_slug'), table_name='securities_exchange')
    op.drop_index(op.f('ix_securities_exchange_name'), table_name='securities_exchange')
    op.drop_table('securities_exchange')
    op.drop_table('live_stock_data')
    op.drop_index(op.f('ix_country_slug'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
