# Generated by Django 3.2.2 on 2021-05-16 12:39

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockexchangecompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'stockexchangecompany',
                'managed': settings.IS_TESTING,
                
            },
        ),
        migrations.CreateModel(
            name='Stockprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_trading.stockexchangecompany')),
            ],
            options={
                'db_table': 'stockprice',
                'managed': settings.IS_TESTING
            },
        ),
    ]
