# Generated by Django 4.1 on 2022-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False, 'ordering': ['category']},
        ),
    ]
